[workspace]
members = ["dtlvnative-sys", "dtlvnative"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "EPL-2.0"
publish = false

[workspace.dependencies]
bindgen = "=0.72.1"
cc = "1.2"
tempfile = "3"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
